### ISSUE TITLE
🔥

### ISSUE THREAD

**Issue by H3XDaemon** [Xposed-Modules-Repo/cn.geektang.privacyspace#1]
啟用重啟後手機直接燒起來
LSPosed log噴到 - - - -part 3315 start- - - -
系統OxygenOS Android 11

**Comment by GeekTR** [comment]
重复

**Comment by tomatolei** [comment]
我装了1.3版本发现会卡死，卸载了就好了，安卓12，三星S20！手机发热电池温度到37度，正常是20！

**Comment by GeekTR** [comment]
> 我装了1.3版本发现会卡死，卸载了就好了，安卓12，三星S20！手机发热电池温度到37度，正常是20！

部分手机上会出现死循环，正在加紧解决

**Comment by GeekTR** [comment]
> 我装了1.3版本发现会卡死，卸载了就好了，安卓12，三星S20！手机发热电池温度到37度，正常是20！

已修复
