### ISSUE TITLE
root permission issue & magisk flashing modules issue

### ISSUE THREAD

**Issue by Hamood111** [Xposed-Modules-Repo/cn.geektang.privacyspace#11]
I had a problem with Root permission when i click restart launcher show me some numbers and telling me the process is denied I can't git root permission but I'm still using 1.3.7 work fine on Android 12 but on 13 both of version when I hide magisk I can't flash any module until remove the hide need more work but still the best of the best apps thank u

**Comment by GeekTR** [comment]
Add ”Magisk“ to the whitelist

**Comment by Hamood111** [comment]
> Add ”Magisk“ to the whitelist

yes it's work 😊 thanks a lot
