### ISSUE TITLE
功能优化建议

### ISSUE THREAD

**Issue by LeslieSong** [Xposed-Modules-Repo/cn.geektang.privacyspace#2]
针对版本：1.3.4
操作系统：Android 12
手机：Google Pixel 4XL
1. 添加应用后，主界面最好保留个“+”图标，减少右上角菜单操作
2. 右上角菜单中“重启系统”操作与“重启桌面”挨的太近，太容易误触，且当前重启没有确认弹窗，一不小心就把手机重启了，建议将重启按钮放最后，且加上确认弹窗。
3. 应用添加进去后，所有的权限都没有了，比如图片类应用无法读写本地存储。

**Comment by GeekTR** [comment]
OK，没有权限这个bug我尽快确认一下。建议也很棒，会在接下来的版本陆续加上

**Comment by GeekTR** [comment]
![WechatIMG11](https://user-images.githubusercontent.com/13369103/159121366-4fca9591-ebba-4dca-b986-b9f39506e548.jpeg)
pixel5，Android12，在白名单中添加此app后被隐藏的app可以正常获取权限。后续版本将把此应用加入内置白名单
