### ISSUE TITLE
致盲是否是让所选应用检测不到其他应用？

### ISSUE THREAD

**Issue by Sfssup** [Xposed-Modules-Repo/cn.geektang.privacyspace#3]
如果是这样的话那就太赞了！后面加个新应用自动致盲，岂不是无敌

**Comment by GeekTR** [comment]
是这样的，但是致盲（也不关联的话）也意味着无法使用微信、支付宝的三方登录、分享以及支付功能。新应用自动致盲这个我还需要考虑考虑

**Comment by EatmeIon** [comment]
致盲牛逼，国产毒瘤只能加关联列表了

**Comment by Sfssup** [comment]
> 是这样的，但是致盲（也不关联的话）也意味着无法使用微信、支付宝的三方登录、分享以及支付功能。新应用自动致盲这个我还需要考虑考虑

致盲牛逼，国产毒瘤只能加关联这个没啥办法
