### ISSUE TITLE
Hide modules LSPosed

### ISSUE THREAD

**Issue by aaref1234** [Xposed-Modules-Repo/cn.geektang.privacyspace#4]
I hid Firefds Kit and XposedSmsCode and they are hidden and The modules are working but they are not active  .

**Comment by GeekTR** [comment]
Sorry, I don't have a Samsung phone so I don't know where the bug is.

**Comment by GeekTR** [comment]
Maybe you can try whitelist all system apps.

**Comment by GeekTR** [comment]
or Connected to all system apps.

**Comment by aaref1234** [comment]
Thank you .
