### ISSUE TITLE
Add an option for hiding the icon launcher 

### ISSUE THREAD

**Issue by MuhammadBayiz** [Xposed-Modules-Repo/cn.geektang.privacyspace#5]
Hi having an option for hiding the launcher it's necessary for some user especially that now we can bypass hiding icon from Android Q 10 and up with lsposed and also enter module setting inside Lsposed Manager itself as a organized person i prefer having all my modules inside lsposed and be able to configure them there too the icon in the launcher isn't necessary because once you configured the module you don't need to open the module as a daily basis like other app so i hope you consider adding it

**Comment by GeekTR** [comment]
You can do this by hiding the "Privacy Space" app itself.
