### ISSUE TITLE
tracking modules

### ISSUE THREAD

**Issue by IzzySoft** [Xposed-Modules-Repo/cn.geektang.privacyspace#6]
For a module carrying the term "privacy" in its name, it looks a bit strage that it comes with 2 tracking modules inside:

```
Offending libs:
---------------
* Microsoft Appcenter Analytics (/com/microsoft/appcenter/analytics): Tracking
* Microsoft Appcenter Crashes (/com/microsoft/appcenter/crashes): Tracking

2 offenders.
```

Especially as MS is not exactly known to be a defender of OUR privacy. Would it be possible to have a build flavor (and APK) coming without those two? Thanks in advance!

**Comment by GeekTR** [comment]
I need to use this SDK to collect crash information from the app. If you don't like it, you can turn off this feature within the app (version 1.3.10 and later).

**Comment by IzzySoft** [comment]
> I need to use this SDK to collect crash information from the app.

And that can only be done by that SDK? Maybe one of the [FOSS alternatives](https://gitlab.com/-/snippets/1896503#acceptable-analytics) could substitute? For collecting crash details, many projects use [ACRA](https://github.com/ACRA/acra) configured to ask the user when a crash happens, so they not only have a word on **if** something is sent, but can also see **what** would be sent.

> If you don't like it, you can turn off this feature

Sorry, but from a privacy perspective, that's not enough – especially not with software having root powers and sending data to a company like MS, Google, etc. Especially when root enters the game, extra care needs to be taken. Even more so if it's software that should enhance privacy :wink: For those with strong feelings towards privacy, this is something keeping them away from using it.

So may I suggest switching to a more privacy-friendly alternative?

**Comment by IzzySoft** [comment]
PS, and concerning MS receiving all the reports (if you ever had to use their latest software, you know they love to collect data on their "customers"), may I quote your Readme?

> Why should we tell software vendors something as personal as which apps are installed?

:wink:

PPS: for point 5 in "Notice", for an "emergency uninstall", it might be a useful hint that one also can use

    adb wait-for-device uninstall cn.geektang.privacyspace

making the timing less crucial.

**Comment by GeekTR** [comment]
Thank you for your suggestions. I will replace Microsoft's SDK with [acra](https://github.com/ACRA/acra) in the next version. Since this is my first time working with acra, it may take some time for me to become familiar with it. As for the other points you mentioned, I will try to make the necessary modifications. Thanks again.

**Comment by IzzySoft** [comment]
Thanks a lot! Can you give me a ping please when the version with ACRA is out? :star_struck:

**Comment by GeekTR** [comment]
OK
