### ISSUE TITLE
Not work on android 13

### ISSUE THREAD

**Issue by Eugienskay** [Xposed-Modules-Repo/cn.geektang.privacyspace#7]
Module can't run on android 13
![Screenshot_20221123-191647](https://user-images.githubusercontent.com/98691796/203545006-3e429593-5c59-4fed-bff6-27e251d52ebd.png)
![Screenshot_20221123-191644_Shell](https://user-images.githubusercontent.com/98691796/203545016-0c6cfbeb-16e7-48ff-93a8-565624e15ec2.png)

**Comment by DineshValor** [comment]
Working on Android 12 or not?

**Comment by DineshValor** [comment]
Because Author only mentioned Android 8-10 supported. Never talk about Android 11-13 🥲

**Comment by castorwong** [comment]
> Working on Android 12 or not?

Yes, working well on Android 12,but not on Android 13

**Comment by DineshValor** [comment]
> > Working on Android 12 or not?
> 
> Yes, working well on Android 12,but not on Android 13

👌

**Comment by GeekTR** [comment]
Please download the latest version.
