### ISSUE TITLE
Explanation of hide feature

### ISSUE THREAD

**Issue by iripu** [Xposed-Modules-Repo/cn.geektang.privacyspace#9]
What exactly hide app do among the below? It's not clear from the description readme. Suppose I hide an app named ABC, now what will happen from below:

1. Other installed apps can't see ABC
2. System apps can't see ABC
3. ABC can't see other installed apps
4. ABC can't see the system apps

Same with whitelist apps. What does whitelisted apps do?

**Comment by GeekTR** [comment]
1
